In [1]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd

In [23]:
class Perceptron:
    def __init__(self,eta,epochs):
        self.weights = np.random.randn(3) * 1e-4
        print(f"self.weights: {self.weights}")
        self.eta = eta
        self.epochs = epochs

    def activationFunction(self,inputs,weights):
        z = np.dot(inputs,weights)
        return np.where(z > 0, 1, 0)

    def fit(self,X,y):
        self.X = X
        self.y = y

        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X_with_bias: \n{X_with_bias}")

        for epochs in range(self.epochs):
            print(f"for epochs: {epochs}")
            y_hat = self.activationFunction(X_with_bias, self.weights)
            print(f"predicted value: \n{y_hat}")
            error = self.y - y_hat
            print(f"error: \n{error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,error)
            print(f"updated weights: \n{self.weights}")

    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
        return self.activationFunction(X_with_bias, self.weights)

# AND operation

In [24]:
data = {"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,0,0,1]}

AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [25]:
X = AND.drop("y",axis=1)
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [26]:
y = AND["y"]
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [27]:
model = Perceptron(eta=0.5,epochs=10)
model.fit(X,y)

self.weights: [-7.92662030e-06 -3.12826538e-06 -1.44358029e-04]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epochs: 0
predicted value:
[1 1 1 1]
error:
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[-0.50000793 -0.50000313  1.49985564]
for epochs: 1
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[-7.92662030e-06 -3.12826538e-06  9.99855642e-01]
for epochs: 2
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.49999207 0.49999687 0.49985564]
for epochs: 3
predicted value:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[-7.92662030e-06 -3.12826538e-06  1.49985564e+00]
for epochs: 4
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.49999207 0.49999687 0.99985564]
for epochs: 5
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49999207 0.49999687 0.99985564]
for epochs: 6
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49999207 0.49999687 0.99985564]
for epochs: 7
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49999207 0.49999687 0.99985564]
for epochs: 8
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49999207 0.49999687 0.99985564]
for epochs: 9
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49999207 0.49999687 0.99985564]

In [28]:
model.predict(X)

array([0, 0, 0, 1])

In [30]:
model.weights

array([0.49999207, 0.49999687, 0.99985564])

# OR operation

In [31]:
data = {"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,1,1,1]}

OR = pd.DataFrame(data)
OR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [34]:
X = OR.drop("y",axis=1)
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [35]:
y = OR["y"]
y.to_frame()

   y
0  0
1  1
2  1
3  1

In [36]:
model = Perceptron(eta=0.5,epochs=10)
model.fit(X,y)

self.weights: [-3.58943838e-05 -5.47295740e-05 -1.92578479e-04]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epochs: 0
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[-3.58943838e-05 -5.47295740e-05  4.99807422e-01]
for epochs: 1
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights:
[ 0.99996411  0.99994527 -1.00019258]
for epochs: 2
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[ 0.99996411  0.99994527 -0.50019258]
for epochs: 3
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[ 9.99964106e-01  9.99945270e-01 -1.92578479e-04]
for epochs: 4
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99996411 0.99994527 0.49980742]
for epochs: 5
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99996411 0.99994527 0.49980742]
for epochs: 6
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99996411 0.99994527 0.49980742]
for epochs: 7
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99996411 0.99994527 0.49980742]
for epochs: 8
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99996411 0.99994527 0.49980742]
for epochs: 9
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99996411 0.99994527 0.49980742]

In [37]:
model.predict(X)

array([0, 1, 1, 1])

In [38]:
model.weights

array([0.99996411, 0.99994527, 0.49980742])

# XOR operation

In [39]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,0]}

XOR = pd.DataFrame(data)
XOR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [40]:
X = XOR.drop("y", axis=1) # axis = 1 >>> dropping across column
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [41]:
y = XOR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  0

In [42]:
model = Perceptron(eta = 0.5, epochs=50)
model.fit(X,y)

self.weights: [ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epochs: 0
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 1
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 2
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 3
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 4
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 5
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 6
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 7
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 8
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 9
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 10
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 11
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 12
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 13
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 14
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 15
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 16
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 17
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 18
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 19
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 20
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 21
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 22
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 23
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 24
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 25
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 26
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 27
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 28
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 29
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 30
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 31
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 32
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 33
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 34
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 35
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 36
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 37
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 38
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 39
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 40
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 41
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 42
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 43
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 44
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 45
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 46
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 47
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]
for epochs: 48
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.50002045  0.49988901 -0.99997832]
for epochs: 49
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[ 2.04472755e-05 -1.10992621e-04  2.16809376e-05]

In [43]:
model.predict(X)

array([0, 0, 0, 0])

In [44]:
model.weights

array([ 2.04472755e-05, -1.10992621e-04,  2.16809376e-05])